apiVersion: core.choreo.dev/v1
kind: Project
metadata:
  annotations:
    core.choreo.dev/description: ${{ values.description }}
    core.choreo.dev/display-name: Customer Portal
  labels:
    core.choreo.dev/name: ${{ values.project_name }}
    core.choreo.dev/organization: default-org
  name: ${{ values.project_name }}
  namespace: default-org
spec:
  deploymentPipelineRef: default-pipeline
