apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.component_name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: ${{ values.repo_owner }}/${{ values.repo_name }}
    backstage.io/kubernetes-label-selector: 'core.choreo.dev/component=${{ values.component_name }},core.choreo.dev/organization=default-org,core.choreo.dev/project=${{ values.project_name }}'
  tags:
    - react 
    - openchoreo
  labels:
    core.choreo.dev/name: ${{ values.component_name }}
    core.choreo.dev/organization: ${{ values.organization_name }}
    core.choreo.dev/project: ${{ values.project_name }}
  links:
    - url: https://github.com/${{ values.repo_owner }}/${{ values.repo_name }}
      title: GitHub Repo
      icon: github
    - url: https://github.com/openchoreo/openchoreo
      title: OpenChoreo
      icon: web
spec:
  type: website
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: ${{ values.project_name }}