name: Build and Push to GHCR

on:
  workflow_dispatch:  # manually trigger from GitHub UI
  push:
    branches: main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: $${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: $${{ github.workspace }}/kubeconfig.yaml
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: $${{ env.REGISTRY }}
          username: $${{ github.actor }}
          password: $${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: $${{ env.REGISTRY }}/$${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: $${{ steps.meta.outputs.tags }}
          labels: $${{ steps.meta.outputs.labels }}

      # - name: Deploy to OpenChoreo
      #   run: |
      #     curl -X POST "https://3a8600b737ff.ngrok.app/deployments" \
      #       -H "Content-Type: application/json" \
      #       --data @.github/deploy_component_request.json

      # - name: Set up kubeconfig
      #   run: |
      #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml

      # - name: Verify k8s cluster connection
      #   run: kubectl get nodes

      # - name: Apply OpenChoreo manifests
      #   run: kubectl apply -f openchoreo.yaml