name: Build and Push to GHCR

on:
  workflow_dispatch:  # manually trigger from GitHub UI
  push:
    branches: main

env:
  REGISTRY: ghcr.io
  {% raw %}
  IMAGE_NAME: ${{ github.repository }}
  {% endraw %}

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      {% raw %}
      KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      {% endraw %}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          {% raw %}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          {% endraw %}

      - name: Get short SHA
        id: vars
        {% raw %}
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"
        {% endraw %}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          {% raw %}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          {% endraw %}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          {% raw %}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          {% endraw %}

      - name: Deploy component version to OpenChoreo
        run: |
          curl -X POST "{% raw %}${{ vars.OPENCHOREO_CP_URL }}{% endraw %}/deployments" \
            -H "Content-Type: application/json" \
            --data '{
              "org_name": "{{ values.organization_name }}",
              "project_name": "{{ values.project_name }}",
              "component_name": "{{ values.component_name }}",
              "deployment_track": "main",
              "score_file_path": "https://raw.githubusercontent.com/{{ values.repo_owner }}/{{ values.repo_name }}/refs/heads/main/score.yaml",
              "extension_file_path": "https://raw.githubusercontent.com/{{ values.repo_owner }}/{{ values.repo_name }}/refs/heads/main/openchoreo.score.yaml",
              "image": "ghcr.io/{{ values.repo_owner }}/{{ values.repo_name }}:{% raw %}${{ env.SHORT_SHA }}{% endraw %}"
            }'
