apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-template
  title: Create React App Component
  description: Create a new React WebApp component
  tags:
    - react
    - cra
    - openchoreo
spec:
  owner: guests
  type: website
  parameters:
    - title: OpenChoreo Component Details
      required:
        - owner
        - organization_name
        - project_name
        - component_name
        - component_type
      properties:
        component_name:
          title: Component Name
          type: string
          description: Name of the component
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this component is for.
        project_name:
          title: Project Name
          type: string
          description: OpenChoreo project name
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: System
        organization_name:
          title: Organization Name
          type: string
          description: OpenChoreo
        component_type:
          title: Component Type
          type: string
          description: Describe the type of component you are creating
          enum:
            - Service
            - WebApplication
            - ManualTask
            - ScheduledTask
        owner:
          title: Owner
          type: string
          description: Owner of the project
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Group
                spec.type: team
    - title: Github Repository Details
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        # copyWithoutRender:
          # - .github/workflows/*
        values:
          component_name: ${{ parameters.component_name }}
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl }}
          owner: ${{ parameters.owner }}
          project_name: ${{ parameters.project_name.split('/')[1] }}
          organization_name: ${{ parameters.organization_name }}
          repo_owner: ${{ parameters.repoUrl.split('owner=')[1].split('&')[0] }}
          repo_name: ${{ parameters.repoUrl.split('repo=')[1] }}

    - id: create-openchoreo-component
      name: Create OpenChoreo Component
      action: openchoreo:component:create
      input:
        orgName: ${{ parameters.organization_name }}
        projectName: ${{ parameters.project_name.split('/')[1] }}
        componentName: ${{ parameters.component_name }}
        description: ${{ parameters.description }}
        componentType: ${{ parameters.component_type }}
        repositoryUrl: ${{ parameters.repoUrl }}
        repositoryBranch: 'main'

    - id: publish
      name: Create Component Repository
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.component_name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public
        protectDefaultBranch: false
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: sameera.madushan@gmail.com

    - id: register
      name: Register OpenChoreo Component in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}