apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-openchoreo-project
  title: Create Project
  description: Create a new OpenChoreo project
  tags:
    - openchoreo
spec:
  owner: web@example.com
  type: system
  parameters:
    - title: Provide some simple information
      required:
        - owner
        - project_name
      properties:
        project_name:
          title: Project Name
          type: string
          description: Name of the project
          ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this project is for.
        owner:
          title: Owner
          type: string
          description: Owner of the project
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Group
                spec.type: team
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          description: ${{ parameters.description }}
          destination: ${{ parameters.repoUrl }}
          owner: ${{ parameters.owner.split('/')[1] }}
          project_name: ${{ parameters.project_name }}
          repo_owner: ${{ parameters.repoUrl.split('owner=')[1].split('&')[0] }}
          repo_name: ${{ parameters.repoUrl.split('repo=')[1] }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.project_name }}
        repoUrl: ${{ parameters.repoUrl }}
        defaultBranch: main
        repoVisibility: public
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: sameera.madushan@gmail.com

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}